# Setup
title:               Coders Blog
tagline:             ''
#description:         ''
baseurl:             ''
paginate:            5

# About/contact
author:
name:                Dean
url:                 http://www.D-sha.github.io

# Custom vars
version:             1.0.0

site:
github:
repo: https://github.com/D-sha/D-sha.github.io

plugins_dir:
  - jekyll-seo-tag