gems:
  - jekyll-seo-tag

# Setup
title:               Coders Blog
tagline:             ''
description:         A blog where I log my technical activities with some code thrown in for good measure
baseurl:             ''
paginate:            1

# About/contact
author:
  twitter:           TeckAllDaThings
name:                Dean
url:                 http://www.D-sha.github.io

# Custom vars
version:             1.0.0


site:
  github:
    repo: https://github.com/D-sha/D-sha.github.io

